services:
  texture2paint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: texture2paint
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped
